# Generated by Django 3.0 on 2020-01-13 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escBackend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Process',
        ),
        migrations.CreateModel(
            name='ProcessComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escBackend.Comment')),
                ('Process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escBackend.Process')),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='ProcessComments',
            field=models.ManyToManyField(through='escBackend.ProcessComments', to='escBackend.Comment'),
        ),
    ]
