# Generated by Django 3.0 on 2019-12-19 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stageTitle', models.CharField(choices=[('E0S1', 'E0Stage1'), ('E0S2', 'E0Stage2'), ('E0S3', 'E0Stage3'), ('E0S4', 'E0Stage4'), ('E1S1', 'E1Stage1'), ('E1S2', 'E1Stage2'), ('E1S3', 'E1Stage3'), ('E1S4', 'E1Stage4'), ('E1S0', 'BackUp')], max_length=4)),
                ('result', models.CharField(choices=[('OG', 'On-going'), ('PS', 'Pass'), ('NP', 'No Pass')], max_length=2)),
                ('comment_text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(choices=[('SE', 'Support Engineer'), ('SEE', 'Support Escalation Engineer'), ('EE', 'Escalation Engineer')], max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HighLvl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('E0', 'Escalation to SEE'), ('E1', 'Escalat\x08ion to EE')], max_length=2)),
                ('status', models.CharField(choices=[('S1', 'Stage1'), ('S2', 'Stage2'), ('S3', 'Stage3'), ('S4', 'Stage4'), ('PS', 'Pass'), ('NP', 'No Pass')], max_length=2)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escdemo.Engineer')),
            ],
            options={
                'ordering': ['engineer'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('E0S1', 'E0Stage1'), ('E0S2', 'E0Stage2'), ('E0S3', 'E0Stage3'), ('E0S4', 'E0Stage4'), ('E1S1', 'E1Stage1'), ('E1S2', 'E1Stage2'), ('E1S3', 'E1Stage3'), ('E1S4', 'E1Stage4'), ('E1S0', 'BackUp')], max_length=4)),
                ('status', models.CharField(choices=[('OG', 'On-going'), ('PS', 'Pass'), ('NP', 'No Pass')], max_length=2)),
                ('commitee_num', models.IntegerField()),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escdemo.Engineer')),
            ],
            options={
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='StageLinkComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escdemo.Comment')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escdemo.Stage')),
            ],
        ),
        migrations.AddField(
            model_name='stage',
            name='related_comment',
            field=models.ManyToManyField(through='escdemo.StageLinkComment', to='escdemo.Comment'),
        ),
        migrations.CreateModel(
            name='ProcessLinkStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escdemo.Process')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escdemo.Stage')),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='stage',
            field=models.ManyToManyField(through='escdemo.ProcessLinkStage', to='escdemo.Stage'),
        ),
        migrations.CreateModel(
            name='MakeCommentOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escdemo.Comment')),
                ('highlvl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escdemo.HighLvl')),
            ],
        ),
        migrations.AddField(
            model_name='highlvl',
            name='related_comment',
            field=models.ManyToManyField(through='escdemo.MakeCommentOn', to='escdemo.Comment'),
        ),
        migrations.AddField(
            model_name='highlvl',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escdemo.Engineer'),
        ),
    ]
