# Generated by Django 3.0 on 2019-12-05 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(choices=[('SE', 'Support Engineer'), ('SEE', 'Support Escalation Engineer'), ('EE', 'Escalation Engineer')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('E1', 'Escalation to SEE'), ('E2', 'Escalat\x08ion to EE')], max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('alive', 'In Process'), ('pass', 'Pass'), ('no_pass', 'No Pass')], max_length=7)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escapp.Engineer')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('S1', 'Stage1'), ('S2', 'Stage2'), ('S3', 'Stage3'), ('S4', 'Stage4'), ('S5', 'Stage5')], max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('alive', 'In Process'), ('pass', 'Pass'), ('no_pass', 'No Pass')], max_length=7)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escapp.Process')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('alive', 'In Process'), ('pass', 'Pass'), ('no_pass', 'No Pass')], max_length=7)),
                ('comment_text', models.CharField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escapp.Engineer')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escapp.Stage')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
