# Generated by Django 3.0 on 2019-12-04 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_a_process', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='date started')),
                ('end_date', models.DateTimeField(verbose_name='date ended')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jadeK.Engineer')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='date started')),
                ('end_date', models.DateTimeField(verbose_name='date ended')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jadeK.Process')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jadeK.Engineer')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jadeK.Stage')),
            ],
        ),
    ]
