# Generated by Django 3.0 on 2019-12-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadeK', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='result',
            field=models.CharField(choices=[('alive', 'In Process'), ('pass', 'Pass'), ('no_pass', 'No Pass')], default=('alive', 'In Process'), max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engineer',
            name='name',
            field=models.CharField(default='default_name', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engineer',
            name='title',
            field=models.CharField(choices=[('SE', 'Support Engineer'), ('SEE', 'Support Escalation Engineer'), ('EE', 'Escalation Engineer')], default=('UDF', 'Undefined Title'), max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='current_stage',
            field=models.CharField(choices=[('S1', 'Stage1'), ('S2', 'Stage2'), ('S3', 'Stage3'), ('S4', 'Stage4'), ('S5', 'Stage5')], default=('UDF', 'Undefined Title'), max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='title',
            field=models.CharField(choices=[('E1', 'Escalation to SEE'), ('E2', 'Escalat\x08ion to EE')], default=('UDF', 'Undefined Title'), max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stage',
            name='status',
            field=models.CharField(choices=[('alive', 'In Process'), ('pass', 'Pass'), ('no_pass', 'No Pass')], default=('UDF', 'Undefined Title'), max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stage',
            name='title',
            field=models.CharField(choices=[('S1', 'Stage1'), ('S2', 'Stage2'), ('S3', 'Stage3'), ('S4', 'Stage4'), ('S5', 'Stage5')], default=('UDF', 'Undefined Title'), max_length=3),
            preserve_default=False,
        ),
    ]
