# Generated by Django 3.0 on 2019-12-04 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jadeK', '0002_auto_20191204_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='end_date',
        ),
    ]
