# Generated by Django 3.0 on 2019-12-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jadeK', '0003_auto_20191204_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='start_date',
        ),
    ]
